name: power-smash
base: core22
version: '0.1.0'
summary: Hit the block at the right time
description: |
  A game where you watch a wooden box fly!

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  power-smash:
    command: power-smash
    extensions: [gnome]
    plugs: [home, network, removable-media, unity7]
      
parts:
  power-smash:
    plugin: dump
    source: ./builds/
    source-type: local
    stage-packages:
      - libglu1-mesa
      - libxcursor1
      - libxinerama1
      - libxrandr2
      - libxi6
      - libpulse0
    override-build: |
      snapcraftctl build
      chmod +x $SNAPCRAFT_PART_INSTALL/power-smash

layout:
  /usr/share/power-smash:
    bind: $SNAP/usr/share/power-smash
